name: python-ml
dependencies:
- python=3.9
- numpy
- scikit-learn
- pandas
- matplotlib
- jupyter
- cython
- nltk
- flask
- wtforms
- seaborn
- pydot
- imageio
- scipy

- pip:
  - tensorflow==latest
  - watermark  
  - pyprind
