name: python-ml
dependencies:
- python=3.9
- numpy
- scikit-learn-intelex
- pandas
- matplotlib
- jupyter
- cython
- nltk
- flask
- wtforms
- seaborn
- pydotplus
- imageio
- scipy
- tpot
- graphviz
- pyparsing
- tensorflow==latest
- watermark  
- pyprind
